package com.walmart.challenge.controller;

import com.walmart.challenge.dto.AddItemRequest;
import com.walmart.challenge.dto.CartDetailsResponse;
import com.walmart.challenge.dto.CreateCartRequest;
import com.walmart.challenge.entity.Cart;
import com.walmart.challenge.service.CartService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;

@RestController
@RequestMapping("/v1/cart")
@RequiredArgsConstructor
@Slf4j
public class CartController {

    private final CartService cartService;

    /**
     * Initializes a new shopping cart resource.
     * Returns a 201 Created status with the Location header pointing to the newly created resource.
     * The cart ID is generated by the server.
     *
     * @param request the initialization data for the cart
     * @return the details of the created cart
     */
    @PostMapping
    public ResponseEntity<CartDetailsResponse> createCart(@Valid @RequestBody CreateCartRequest request) {
        log.info("REST request to create a new cart");

        Cart cart = cartService.createCart(request);
        String cartId = cart.getId().toString();

        var response = cartService.getCart(cartId);

        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(cartId)
                .toUri();

        return ResponseEntity.created(location).body(response);
    }

    /**
     * Adds an item to an existing cart or updates its quantity if already present.
     * Returns the updated state of the cart to allow immediate UI reflection.
     *
     * @param cartId  identifier of the cart
     * @param request sku and quantity to add
     * @return the updated cart details
     */
    @PostMapping("/{cartId}/items")
    public ResponseEntity<CartDetailsResponse> addItem(@PathVariable String cartId,
                                                       @Valid @RequestBody AddItemRequest request) {
        log.debug("REST request to add item SKU {} to cart {}", request.getSku(), cartId);

        cartService.addItem(cartId, request);
        var response = cartService.getCart(cartId);

        return ResponseEntity.ok(response);
    }

    /**
     * Retrieves the current state of a specific cart.
     *
     * @param cartId identifier of the cart
     * @return cart details including items and totals
     */
    @GetMapping("/{cartId}")
    public ResponseEntity<CartDetailsResponse> getCart(@PathVariable String cartId) {
        log.debug("REST request to fetch details for cart {}", cartId);

        var response = cartService.getCart(cartId);

        return ResponseEntity.ok(response);
    }
}